apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-pv-claim
  annotations:
    volume.beta.kubernetes.io/storage-class: "microk8s-hostpath-storage"
  labels:
    app: hh
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 65Gi
